stages:
  - build

variables:
  AWS_ACCOUNT_ID: "520492793952"
  AWS_REGION: "ap-southeast-1"
  ECR_REGISTRY: "520492793952.dkr.ecr.ap-southeast-1.amazonaws.com"
  ECR_REPO_NAME: "vwa-congtacsinhvien"
  GIT_DEPTH: 1

build_develop:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  tags:
    - runner-vu-digital-dev
  variables:
    KUBERNETES_MEMORY_REQUEST: "2Gi"
    KUBERNETES_MEMORY_LIMIT: "5Gi"
    KUBERNETES_CPU_REQUEST: "1"
    KUBERNETES_CPU_LIMIT: "3"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME =~ /^uat(-.+)?$/)
  script:
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json << DOCKEREOF
      {
        "credHelpers": {
          "${ECR_REGISTRY}": "ecr-login"
        }
      }
      DOCKEREOF
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${ECR_REGISTRY}/${ECR_REPO_NAME}:${CI_COMMIT_SHORT_SHA}"
      --destination "${ECR_REGISTRY}/${ECR_REPO_NAME}:${CI_COMMIT_REF_SLUG}"
      --snapshot-mode=redo
      --use-new-run
      --compressed-caching=false
  interruptible: true
