stages:
  - build
  - update-gitops

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    - when: never

variables:
  AWS_ACCOUNT_ID: "520492793952"
  AWS_REGION: "ap-southeast-1"
  ECR_REGISTRY: "520492793952.dkr.ecr.ap-southeast-1.amazonaws.com"
  ECR_REPO_NAME: "vwa-congtacsinhvien"
  APP_NAME: "dhs-ctsv-web"
  GIT_DEPTH: 1

include:
  - project: 'vsf-qtvhgd/vinuni/digital-university/devsecops/gitops-dev'
    ref: master
    file: '.gitlab/cd-update-image.yml'

build_develop:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  tags:
    - runner-vu-digital-dev
  variables:
    KUBERNETES_MEMORY_REQUEST: "2Gi"
    KUBERNETES_MEMORY_LIMIT: "5Gi"
    KUBERNETES_CPU_REQUEST: "2"
    KUBERNETES_CPU_LIMIT: "4"
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "10Gi"
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "20Gi"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
  script:
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json << DOCKEREOF
      {
        "credHelpers": {
          "${ECR_REGISTRY}": "ecr-login"
        }
      }
      DOCKEREOF
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${ECR_REGISTRY}/vwa-congtacsinhvien:${CI_COMMIT_SHORT_SHA}"
      --destination "${ECR_REGISTRY}/vwa-congtacsinhvien:develop"
      --cache=true
      --cache-repo="${ECR_REGISTRY}/digital-dev-build-cache"
      --snapshot-mode=redo
      --use-new-run
      --compressed-caching=false
      --cleanup
  interruptible: true

update_gitops:
  extends: .update_image_tag
  rules:
    - when: never
  needs:
    - build_develop
