export enum ThuTrongTuan {
	THU_2 = 'Thứ 2',
	THU_3 = 'Thứ 3',
	THU_4 = 'Thứ 4',
	THU_5 = 'Thứ 5',
	THU_6 = 'Thứ 6',
	THU_7 = 'Thứ 7',
	CHU_NHAT = 'Chủ nhật',
}

export enum ELoaiGiaTri {
	GIO = 'Giờ',
	PHUT = 'Phút',
	NGAY = 'Ngày',
}

export enum SettingKey {
	THONG_BAO_SU_KIEN = 'THONG_BAO_SU_KIEN',
	CHUC_NANG_APP_GV = 'CHUC_NANG_APP_GV',
	CHUC_NANG_APP_SV = 'CHUC_NANG_APP_SV',
}

export enum EDanhSachChucNang {
	TINTUC = 'TINTUC',
	LOPHANHCHINH = 'LOPHANHCHINH',
	LOPTINCHI = 'LOPTINCHI',
	DICHVUMOTCUA = 'DICHVUMOTCUA',
	CONGNO = 'CONGNO',
	THUVIEN = 'THUVIEN',
	THONGBAO = 'THONGBAO',
	TOCHUCNHANSU = 'TOCHUCNHANSU',
	LICHCANHAN = 'LICHCANHAN',
	KHAOSATTRUCTUYEN = 'KHAOSATTRUCTUYEN',
	PHANHOI = 'PHANHOI',
	LICHTUANHOCVIEN = 'LICHTUANHOCVIEN',
	KETQUAKHOAHOCCONGNGHE = 'KETQUAKHOAHOCCONGNGHE',
	CAUHOITHUONGGAP = 'CAUHOTHUONGGAP',
	VANBANHUONGDAN = 'VANBANHUONGDAN',
	GIOITHIEU = 'GIOITHIEU',
	SUKIEN = 'SUKIEN',
	KETQUADANGKYHOCPHAN = 'KETQUADANGKYHOCPHAN',
	KETQUAHOCTAP = 'KETQUAHOCTAP',
	TIENTRINHHOCTAP = 'TIENTRINHHOCTAP',
	THOIKHOABIEU = 'THOIKHOABIEU',
	DIEMRENLUYEN = 'DIEMRENLUYEN',
	LICHTHI = 'LICHTHI',
	LOPTINCHI_THONGTINSINHVIEN = 'LOPTINCHI_THONGTINSINHVIEN',
	LOPTINCHI_LOPTHUCHANH = 'LOPTINCHI_LOPTHUCHANH',
	LOPTINCHI_DIENDAN = 'LOPTINCHI_DIENDAN',
	LOPTINCHI_BAITAP = 'LOPTINCHI_BAITAP',
	DANHGIAGIANGVIEN = 'DANHGIAGIANGVIEN',
	DANGKYSACHED = 'DANGKYSACHED',
	THONG_TIN_CA_NHAN = 'THONG_TIN_CA_NHAN',
	DANG_XUAT = 'DANG_XUAT',
	SO_YEU_LY_LICH = 'SO_YEU_LY_LICH',
	FACEID = 'FACEID',
	PTIT_MAP = 'PTIT_MAP',
	DOI_MAT_KHAU = 'DOI_MAT_KHAU',
	DOI_VAI_TRO = 'DOI_VAI_TRO',
	DOI_CON = 'DOI_CON',
}

export const MapTitleEDanhSachChucNang = {
	[EDanhSachChucNang.TINTUC]: 'Tin tức',
	[EDanhSachChucNang.LOPHANHCHINH]: 'Lớp hành chính',
	[EDanhSachChucNang.LOPTINCHI]: 'Lớp tín chỉ',
	[EDanhSachChucNang.DICHVUMOTCUA]: 'Dịch vụ một cửa',
	[EDanhSachChucNang.CONGNO]: 'Công nợ',
	[EDanhSachChucNang.THUVIEN]: 'Thư viện',
	[EDanhSachChucNang.THONGBAO]: 'Thông báo',
	[EDanhSachChucNang.TOCHUCNHANSU]: 'Tổ chức nhân sự',
	[EDanhSachChucNang.LICHCANHAN]: 'Lịch cá nhân',
	[EDanhSachChucNang.KHAOSATTRUCTUYEN]: 'Khảo sát trực tuyến',
	[EDanhSachChucNang.PHANHOI]: 'Phản hồi',
	[EDanhSachChucNang.LICHTUANHOCVIEN]: 'Lịch tuần học viên',
	[EDanhSachChucNang.KETQUAKHOAHOCCONGNGHE]: 'Kết quả khoa học công nghệ',
	[EDanhSachChucNang.CAUHOITHUONGGAP]: 'Câu hỏi thường gặp',
	[EDanhSachChucNang.VANBANHUONGDAN]: 'Văn bản hướng dẫn',
	[EDanhSachChucNang.GIOITHIEU]: 'Giới thiệu',
	[EDanhSachChucNang.SUKIEN]: 'Sự kiện',
	[EDanhSachChucNang.KETQUADANGKYHOCPHAN]: 'Kết quả đăng ký học phần',
	[EDanhSachChucNang.KETQUAHOCTAP]: 'Kết quả học tập',
	[EDanhSachChucNang.TIENTRINHHOCTAP]: 'Tiến trình học tập',
	[EDanhSachChucNang.THOIKHOABIEU]: 'Thời khóa biểu',
	[EDanhSachChucNang.DIEMRENLUYEN]: 'Điểm rèn luyện',
	[EDanhSachChucNang.LICHTHI]: 'Lịch thi',
	[EDanhSachChucNang.LOPTINCHI_THONGTINSINHVIEN]: 'Lớp tín chỉ - Thông tin sinh viên',
	[EDanhSachChucNang.LOPTINCHI_LOPTHUCHANH]: 'Lớp tín chỉ - Lớp thực hành',
	[EDanhSachChucNang.LOPTINCHI_DIENDAN]: 'Lớp tín chỉ - Diễn đàn',
	[EDanhSachChucNang.LOPTINCHI_BAITAP]: 'Lớp tín chỉ - Bài tập',
	[EDanhSachChucNang.DANHGIAGIANGVIEN]: 'Đánh giá giảng viên',
	[EDanhSachChucNang.DANGKYSACHED]: 'Đăng ký sách điện tử',
	[EDanhSachChucNang.THONG_TIN_CA_NHAN]: 'Thông tin cá nhân',
	[EDanhSachChucNang.DANG_XUAT]: 'Đăng xuất',
	[EDanhSachChucNang.SO_YEU_LY_LICH]: 'Sơ yếu lý lịch',
	[EDanhSachChucNang.FACEID]: 'Nhận diện khuôn mặt (FaceID)',
	[EDanhSachChucNang.PTIT_MAP]: 'Bản đồ PTIT',
	[EDanhSachChucNang.DOI_MAT_KHAU]: 'Đổi mật khẩu',
	[EDanhSachChucNang.DOI_VAI_TRO]: 'Đổi vai trò',
	[EDanhSachChucNang.DOI_CON]: 'Đổi con',
};
