export enum SettingKey {
  NGAY_NGHI_BAO_LUU = 'NGAY_NGHI_BAO_LUU',
  KHAI_BO_SUNG = 'KHAI_BO_SUNG',
  LAM_THEM_BUOI_DEM = 'LAM_THEM_BUOI_DEM',
  PHAN_QUYEN = 'PHAN_QUYEN',
  DU_KIEN_LAM_THEM_GIO = 'DU_KIEN_LAM_THEM_GIO',
  THUC_TE_LAM_THEM_GIO = 'THUC_TE_LAM_THEM_GIO',
  DINH_MUC_GIO_CHUAN = 'DINH_MUC_GIO_CHUAN',
}
